### ISSUE TITLE
backupy fail

### ISSUE THREAD

**Issue by seb-taillon** [elesiuta/backupy#2]
root@vm-201:/tmp# sudo backupy / /tmp/ --dry-run                                                   
Dry Run                                                                                            
Scanning files on source:                                                                          
/                                                                                                  
Traceback (most recent call last):                                                                 
  File "/snap/backupy/485/bin/backupy", line 33, in <module>                                       
    sys.exit(load_entry_point('BackuPy==1.8.6', 'console_scripts', 'backupy')())                   
  File "/snap/backupy/485/lib/python3.6/site-packages/backupy/cli.py", line 124, in main           
    return backup_manager.run()                                                                    
  File "/snap/backupy/485/lib/python3.6/site-packages/backupy/backupman.py", line 287, in run      
    self.source.scanDir(self.config.stdout_status_bar)                                             
  File "/snap/backupy/485/lib/python3.6/site-packages/backupy/dirinfo.py", line 215, in scanDir    
    if len(os.listdir(full_path)) == 0:                                                            
PermissionError: [Errno 13] Permission denied: '/bin'

**Comment by elesiuta** [comment]
That's a snap confinement issue, by design they cannot access your files at / and it only has interfaces for home and removable-media.

If you want it to access your /bin directory, you'll need to use the python package that can be installed with pip.
