### ISSUE TITLE
copy fails if there is an error reading the destination folder

### ISSUE THREAD

**Issue by mauromussin** [elesiuta/backupy#4]
In my disk G:\ there is a folder unreadable, so I got:
```
G:\casa_mussin
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mauro\backupy.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mauro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\backupy\cli.py", line 128, in main
    return backup_manager.run()
  File "C:\Users\Mauro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\backupy\backupman.py", line 315, in run
    self.dest.scanDir(self.config.stdout_status_bar)
  File "C:\Users\Mauro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\backupy\dirinfo.py", line 216, in scanDir
    if len(os.listdir(full_path)) == 0:
OSError: [WinError 1392] La directory o il file è danneggiato e illeggibile: 'G:\\casa_mussin\\_X'
PS C:\Users\Mauro>
```

**Comment by elesiuta** [comment]
Thanks for reporting this!  

I was able to replicate a similar issue using permissions, however in your case it looks like the folder is corrupted.  

I'm still thinking about the best way to handle this, if the unreadable folder is the destination for a backup or mirror, any files that were there will simply show up as missing, and trying to copy anything back there from the source will simply result in failed transfers for those files.  

However if the unreadable folder is in the source for a mirror, or either side for a sync with deletions, these files will appear as being deleted and a user not paying attention to the diff could now lose their backup.  

For this reason I think it is safer for BackuPy to throw an error and quit without doing anything. I'm still going to think about this for a bit but I'll likely just catch this error and print a more user friendly message then quit.

If you want it to continue running and just ignore this unreadable folder, you can add it to your config by setting `filter_exclude_list = ["_X"]` or from the command line with `--fe "_X"`
